##Fecha de realización: 16/12/2021

In [ ]:
#Importar librerías
import pandas as pd

In [ ]:
df = pd.read_excel("data2009_manual.xlsx")
df

     Unnamed: 0  ...                                              tweet
0             0  ...  @stellargirl I loooooooovvvvvveee my Kindle2. ...
1             1  ...  Reading my kindle2...  Love it... Lee childs i...
2             2  ...  Ok, first assesment of the #kindle2 ...it fuck...
3             3  ...  @kenburbary You'll love your Kindle2. I've had...
4             4  ...  @mikefish  Fair enough. But i have the Kindle2...
..          ...  ...                                                ...
493         493  ...  Ask Programming: LaTeX or InDesign?: submitted...
494         494  ...  On that note, I hate Word. I hate Pages. I hat...
495         495  ...  Ahhh... back in a *real* text editing environm...
496         496  ...  Trouble in Iran, I see. Hmm. Iran. Iran so far...
497         497  ...  Reading the tweets coming out of Iran... The w...

[498 rows x 7 columns]

In [ ]:
df_final = pd.DataFrame()
df_final["tweet"] = df["tweet"]
df_final["Sentimiento"] = df["Sentimiento"]
df_final

                                                 tweet  Sentimiento
0    @stellargirl I loooooooovvvvvveee my Kindle2. ...            4
1    Reading my kindle2...  Love it... Lee childs i...            4
2    Ok, first assesment of the #kindle2 ...it fuck...            4
3    @kenburbary You'll love your Kindle2. I've had...            4
4    @mikefish  Fair enough. But i have the Kindle2...            4
..                                                 ...          ...
493  Ask Programming: LaTeX or InDesign?: submitted...            2
494  On that note, I hate Word. I hate Pages. I hat...            0
495  Ahhh... back in a *real* text editing environm...            4
496  Trouble in Iran, I see. Hmm. Iran. Iran so far...            0
497  Reading the tweets coming out of Iran... The w...            0

[498 rows x 2 columns]

In [ ]:
def suma1(numero):
  numero = numero + 1
  return numero

In [ ]:
df_final["Sentimiento"] = df_final.Sentimiento.apply(lambda x: suma1(x))

In [ ]:
df_final

                                                 tweet  Sentimiento
0    @stellargirl I loooooooovvvvvveee my Kindle2. ...            5
1    Reading my kindle2...  Love it... Lee childs i...            5
2    Ok, first assesment of the #kindle2 ...it fuck...            5
3    @kenburbary You'll love your Kindle2. I've had...            5
4    @mikefish  Fair enough. But i have the Kindle2...            5
..                                                 ...          ...
493  Ask Programming: LaTeX or InDesign?: submitted...            3
494  On that note, I hate Word. I hate Pages. I hat...            1
495  Ahhh... back in a *real* text editing environm...            5
496  Trouble in Iran, I see. Hmm. Iran. Iran so far...            1
497  Reading the tweets coming out of Iran... The w...            1

[498 rows x 2 columns]

##Tweepy

In [ ]:
from config import *
import tweepy
import datetime
import pandas as pd
import re

In [ ]:
#Sacando variables del archivo config.py que es donde están las claves de mi cuenta de Developer
#de Twitter.
auth = tweepy.OAuthHandler(TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET)
auth.set_access_token(TWITTER_ACCESS_TOKEN, TWITTER_ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)

In [ ]:
#Se usará la fecha actual, y también la fecha hasta el día de ayer
today = datetime.date.today()
date= today - datetime.timedelta(days=1)
today, date

(datetime.date(2021, 12, 17), datetime.date(2021, 12, 16))

In [ ]:
all_tweets = []
palabra = "Ousama ranking"
for tweet in tweepy.Cursor(api.search, q=palabra + " until:" + str(today), tweet_mode ="extended", lang="es").items(100):
  all_tweets.append(tweet.full_text)

In [ ]:
all_tweets[1]

'Os presento a Ousama Ranking, el mejor anime de este año https://t.co/1TPKYYOiXB'

In [ ]:
df_tweepy = pd.DataFrame()
df_tweepy["tweets"] = all_tweets

In [ ]:
df_tweepy

                                               tweets
0   RT @josecoco25: Que maldito bueno es Ousama Ra...
1   Os presento a Ousama Ranking, el mejor anime d...
2   Que maldito bueno es Ousama Ranking. Ni una so...
3   Ahora tengo que verme el epi de Ousama Ranking...
4   Hoy termina Aquatope, y apenas veré el final a...
..                                                ...
95  @rasenkai7 Por cierto si tienes tiempo te reco...
96  @SonyerOriginal Komi me gusta más pero Ousama ...
97  @sginfluenza Pueeees, estoy viendo Kimetsu, Ko...
98  El nuevo avance del décimo episodio de la adap...
99  Ousama Ranking, hasta ahora es 9.50 porque sac...

[100 rows x 1 columns]

In [ ]:
for i in range(df_tweepy.shape[0]):
  nueva_fila = {"tweet": df_tweepy["tweets"][i], "Sentimiento": ""}
  df_final = df_final.append(nueva_fila, ignore_index=True)

In [ ]:
df_final

                                                 tweet Sentimiento
0    @stellargirl I loooooooovvvvvveee my Kindle2. ...           5
1    Reading my kindle2...  Love it... Lee childs i...           5
2    Ok, first assesment of the #kindle2 ...it fuck...           5
3    @kenburbary You'll love your Kindle2. I've had...           5
4    @mikefish  Fair enough. But i have the Kindle2...           5
..                                                 ...         ...
593  @rasenkai7 Por cierto si tienes tiempo te reco...
594  @SonyerOriginal Komi me gusta más pero Ousama ...
595  @sginfluenza Pueeees, estoy viendo Kimetsu, Ko...
596  El nuevo avance del décimo episodio de la adap...
597  Ousama Ranking, hasta ahora es 9.50 porque sac...

[598 rows x 2 columns]

In [ ]:
today = datetime.date.today()
date= today - datetime.timedelta(days=7)
today, date

(datetime.date(2021, 12, 17), datetime.date(2021, 12, 10))

In [ ]:
all_tweets = []
palabra = "#JuntosPorElEmpleo"
for tweet in tweepy.Cursor(api.search, q=palabra + " until:" + str(today), tweet_mode ="extended", lang="es").items(100):
  all_tweets.append(tweet.full_text)

In [ ]:
df_tweepy = pd.DataFrame()
df_tweepy["tweets"] = all_tweets

In [ ]:
df_tweepy

                                               tweets
0   @sigridbazan Ud. y su grupete político, odiado...
1   A que partido se irá? a #JuntosPorElEmpleo = @...
2   @miguel957 @bancadaJP @sigridbazan @RuthLuqueI...
3   @Vero_Mendoza_F Todos uds son una sarta de com...
4   #LOULTIMO este técnico "imparcial" digno cavia...
5   @tuesta @KikesitoRPP @RPPNoticias Jkajaja qué ...
6   @EIPeruano 🤡🤡😂😂 se quieren tumbar como sea al ...
7   RT @JChuquicondor: @IzquierdaPeOOC #JuntosPorE...
8   @sigridbazan Salió a decir que era “leal” a lo...
9   RT @JChuquicondor: @sigridbazan #JuntosPorElEm...
10  @bancadaJP @sigridbazan @RuthLuqueIbarra @chab...
11     @sigridbazan #JuntosPorElEmpleo recontra 🐚🐚🐚🐚🐚
12  @bancadaJP @sigridbazan @RuthLuqueIbarra @chab...
13  RT @StefannyH2000: @rosangellafp @congresoperu...
14  RT @caviaresbicente: Se les cayó el #ComplotCo...
15  RT @caviaresbicente: Bueno, y como era de espe...
16  @spaciolibre @MaricarmenAlvaP Las mentiras ent...
17  @parapioggia Fuera Podemos de España y Bermejo...
18  @rosangellafp @congresoperu Que buena interven...
19  @pedrojosecama Es que Podemos es un partido es...
20  @KikesitoRPP @sigridbazan @JuntosporPeru @RPPN...
21  @IzquierdaPeOOC #JuntosPorElEmpleo precisa la ...
22  @sigridbazan 🤣🤣🤣🤣🤣🤣 que conchuda carajo!!! Raz...
23  Se les cayó el #ComplotComunista \nQue mentía ...
24  Sigrid antes de ser congresista no conocía los...
25  Bueno, y como era de esperarse, su plan macabr...
26  Hasta Puka con todo y sus cantinfladas apoya a...
27  RT @caviaresbicente: Se les cayó el #ComplotCo...
28  RT @caviaresbicente: Se les cayó el #ComplotCo...
29  Se les cayó el #ComplotComunista \nPodemos es ...
30  @aaronsalomong 👍 @CarlosAnderso1 por decirle l...
31  @KikesitoRPP @CarlosAnderso1 @JuntosporPeru @R...
32  Bermejo y Sigrid Bazán fueron los primeros aba...
33  @bancadaJP @sigridbazan @RuthLuqueIbarra @chab...
34  Juntos por el Perú quiso entrar al poder del C...
35  Se les cayó el #ComplotComunista \nPodemos es ...
36  Maria del Carmen Alva saliendo respaldada en f...
37  Bancadas del @congresoperu no le hagan caso a ...
38  Bien @CarlosAnderso1 por decirle a @bancadaJP ...
39  @RPPNoticias Jajajaja #JuntosPorElEmpleo!! 😂😂😂...
40  @VLADIMIR_CERRON Pero #JuntosPorElEmpleo, te q...
41   #TuCongresoInforma, muy buena #JuntosPorElEmpleo
42  #juntosporelempleo el partido de @JuntosporPer...
43  @Renzoiban Congresista @CarlosAnderso1 buena #...
44  #JuntosPorElEmpleo!!! 😂😂\nDe eso se arañan @Ru...
45  Muy bien dicho, @JuntosporPeru ahora se llama ...

In [ ]:
for i in range(df_tweepy.shape[0]):
  nueva_fila = {"tweet": df_tweepy["tweets"][i], "Sentimiento": ""}
  df_final = df_final.append(nueva_fila, ignore_index=True)

In [ ]:
df_final

                                                 tweet Sentimiento
0    @stellargirl I loooooooovvvvvveee my Kindle2. ...           5
1    Reading my kindle2...  Love it... Lee childs i...           5
2    Ok, first assesment of the #kindle2 ...it fuck...           5
3    @kenburbary You'll love your Kindle2. I've had...           5
4    @mikefish  Fair enough. But i have the Kindle2...           5
..                                                 ...         ...
639   #TuCongresoInforma, muy buena #JuntosPorElEmpleo
640  #juntosporelempleo el partido de @JuntosporPer...
641  @Renzoiban Congresista @CarlosAnderso1 buena #...
642  #JuntosPorElEmpleo!!! 😂😂\nDe eso se arañan @Ru...
643  Muy bien dicho, @JuntosporPeru ahora se llama ...

[644 rows x 2 columns]

In [ ]:
df_final.to_excel("dataset.xlsx")

##Cargando el dataset ya procesado manualmente

In [ ]:
df = pd.read_excel("dataset.xlsx", index_col=0)
df

                                                 tweet  Sentimiento
0    @stellargirl I loooooooovvvvvveee my Kindle2. ...            5
1    Reading my kindle2...  Love it... Lee childs i...            5
2    Ok, first assesment of the #kindle2 ...it fuck...            5
3    @kenburbary You'll love your Kindle2. I've had...            5
4    @mikefish  Fair enough. But i have the Kindle2...            5
..                                                 ...          ...
639   #TuCongresoInforma, muy buena #JuntosPorElEmpleo            3
640  #juntosporelempleo el partido de @JuntosporPer...            3
641  @Renzoiban Congresista @CarlosAnderso1 buena #...            5
642  #JuntosPorElEmpleo!!! 😂😂\nDe eso se arañan @Ru...            3
643  Muy bien dicho, @JuntosporPeru ahora se llama ...            3

[644 rows x 2 columns]

In [ ]:
df["Sentimiento"].value_counts()

5    226
3    216
1    202
Name: Sentimiento, dtype: int64

In [ ]:
df = df.drop_duplicates()
df["Sentimiento"].value_counts()

5    223
3    207
1    200
Name: Sentimiento, dtype: int64

In [ ]:
df.to_excel("dataset_tesis.xlsx")